image: archlinux
packages:
  - valgrind
sources:
  - https://git.sr.ht/~klahr/libu8t
  - https://git.sr.ht/~klahr/unit-check
tasks:
  - setup: |
      cd unit-check
      make
      sudo make install
  - build: |
      cd libu8t
      make
  - test: |
      cd libu8t
      cd tests
      make
      valgrind --leak-check=full ./tests

