image: archlinux
packages:
  - valgrind
  - cmake
  - debuginfod
sources:
  - https://git.sr.ht/~klahr/libu8t
  - https://git.sr.ht/~klahr/unit-check
tasks:
  - setup: |
      cd unit-check
      mkdir -p build
      cd build
      cmake ..
      make
      sudo make install
  - build: |
      cd libu8t
      cmake -S . -B build
      cmake --build build
  - run_tests: |
      cd libu8t/build
      ctest -j$(nproc) --output-on-failure
  - run_valgrind: |
      cd libu8t/build
      export DEBUGINFOD_URLS="https://debuginfod.archlinux.org"
      valgrind --leak-check=full ./tests/test_scanner
triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
